# 1 hour cache for gpg keys
default-cache-ttl 3600
max-cache-ttl 3600

pinentry-program /usr/bin/pinentry

# allow terminal/loopback passphrase entry
allow-loopback-pinentry

# disable saving to keychain/credential manager
no-allow-external-cache
