use-agent

# disable pinentry modal popup
pinentry-mode loopback

# gpg reads user inputs (user ID/name/email) from command line as utf-8
utf8-strings

# --- Display ---
# suppress the initial copyright message.
no-greeting
# disable inclusion of the version string in ASCII armored output
no-emit-version
# disable comment string in clear text signatures and ASCII armored messages
no-comments


# display long key IDs
keyid-format 0xlong

# list all keys (or the specified ones) along with their fingerprints
with-fingerprint

# gpg outputs to terminal/user as utf-8
#display-charset utf-8

# --- security ---
# default: automatic key retrieval, only from local machine
auto-key-locate local

# refuse to run if GnuPG cannot get secure memory
# defaults to no (i.e. run, but give a warning)
require-secmem

# default: prevents signature/key substitution when signing subkeys
require-cross-certification

# default: force the use of encryption with a modification detection code.
#force-mdc
