# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# local copy
# "$schema" = "$HOME\\.config\\starship\\starship-theme-schema.json"

# Inserts a blank line between shell prompts
add_newline = false

# === customization ===
continuation_prompt = ">>"

format = "$time $all$character"

[character]
success_symbol = '[ ](bold #f14e32)[❯](bold green)'
error_symbol = '[ ](bold #f14e32)[](bold red)'

[directory]
style = "bold green"
use_os_path_sep = false

[git_branch]
symbol = ""
style = "bold blue"

[git_commit]
tag_disabled = false
tag_symbol = "  "

[git_status]
deleted = '[-${count}](red bold)'
staged = '[+${count}](green bold)'
renamed = '[»${count}](blue bold)'
untracked = '[?${count}](purple bold)'
modified = '[~${count}](yellow bold)'
ahead = '[⇡${count}](blue bold)'
diverged = '[⇕\{⇡${ahead_count}⇣${behind_count}\}](red bold)'
behind = '[⇣${count}](yellow bold)'
conflicted = "\u2262"
stashed = '[${count}](yellow bold)'
format = '([($ahead_behind )\[$all_status\]]($style) )'

#[git_metrics]
#disabled = false

[time]
disabled = false
time_format = "%H:%M"
format = '[$time](white bold)'

[hostname]
ssh_symbol = "@"
format = "[$ssh_symbol$hostname]($style): "
style = "bold yellow"

[username]
format = "[$user]($style)"

# === Disables ===
[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

#[container]
#disabled = true

[package]
disabled = true
