# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# === customization ===
command_timeout = 3000

# Inserts a blank line between shell prompts
add_newline = false

continuation_prompt = ">>"

format = "$time $all$character"

[character]
# ubuntu
# success_symbol = '[ ](bold #E95420)[❯](bold green)'
# error_symbol = '[ ](bold #E95420)[](bold red)'

# arch
# success_symbol = '[ ](bold #1793D1)[❯](bold green)'
# error_symbol = '[ ](bold #1793D1)[](bold red)'

# kali
# success_symbol = '[ ](bold #33627E)[❯](bold green)'
# error_symbol = '[ ](bold #33627E)[](bold red)'

# debian
# success_symbol = '[ ](bold #D70A53)[❯](bold green)'
# error_symbol = '[ ](bold #D70A53)[](bold red)'

# mint
# success_symbol = '[󰣭 ](bold #86BE43)[❯](bold green)'
# error_symbol = '[󰣭 ](bold #86BE43)[](bold red)'

# linux
# success_symbol = '[ ](bold #77216F)[❯](bold green)'
# error_symbol = '[ ](bold #77216F)[](bold red)'

# windows
success_symbol = '[󰍲](bold #00A4EF) [❯](bold green)'
error_symbol = '[󰍲](bold #00A4EF) [](bold red)'

# git bash
# success_symbol = '[ ](bold #F14E32)[❯](bold green)'
# error_symbol = '[ ](bold #F14E32)[](bold red)'

# apple
# success_symbol = '[ ](bold #A2AAAD)[❯](bold green)'
# error_symbol = '[ ](bold #A2AAAD)[](bold red)'

[directory]
style = "bold green"
# Windows: always use `/`
use_os_path_sep = false

[git_branch]
symbol = ""
style = "bold blue"

[git_commit]
tag_disabled = false
tag_symbol = "  "

[git_status]
deleted = '[-${count}](red bold)'
staged = '[+${count}](green bold)'
renamed = '[»${count}](blue bold)'
untracked = '[?${count}](purple bold)'
modified = '[~${count}](yellow bold)'
ahead = '[⇡${count}](blue bold)'
diverged = '[⇕\{⇡${ahead_count}⇣${behind_count}\}](red bold)'
behind = '[⇣${count}](yellow bold)'
conflicted = "\u2262"
stashed = '[${count}](yellow bold)'
format = '([($ahead_behind )\[$all_status\]]($style) )'

#[git_metrics]
#disabled = false

[time]
disabled = false
time_format = "%H:%M"
format = '[$time](white bold)'

[hostname]
ssh_symbol = "@"
format = "[$ssh_symbol$hostname]($style): "
style = "bold yellow"

[username]
format = "[$user]($style) "

# === Disables ===
[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

#[container]
#disabled = true

[package]
disabled = true
